FROM ubuntu:22.04

# Variables
ARG username=terraform
ARG path=/terraform

# Environment
ENV USER=${username}
ENV USERNAME=${username}

# Use user root
USER root

# Create folder
RUN mkdir ${path}

# Install packages
RUN apt update && apt install curl wget sshpass less -y

# Add user terraform
RUN useradd -ms /bin/bash ${username}
RUN chown -R ${username}:${username} ${path}

# Install oh-my-posh
RUN wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
RUN chmod +x /usr/local/bin/oh-my-posh

RUN echo 'eval "$(oh-my-posh init bash --config /terraform/.devcontainer/configuration/terminal.omp.json)"' >> /home/${username}/.bashrc

# User terraform
USER ${username}