name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set image version
        required: true

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  push_docker_image_to_dockerhub:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: moleszek/terraforms:latest
      - name: Build and push with tag ${{ env.VERSION }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: moleszek/terraforms:${{ env.VERSION }}
