name: Generate terraform docs
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

permissions:
  contents: write

jobs:
  generate_documentation:
    name: Generate Terraform documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Linode terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: linode/
          output-file: USAGE.md
          output-method: inject
          git-push: "false"

      - name: Render AWS terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: aws/
          output-file: USAGE.md
          output-method: inject
          git-push: "false"

      - name: Render Azure terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: azure/
          output-file: USAGE.md
          output-method: inject
          git-push: "false"

      - name: Push documentation changes
        run: |
          git config user.email "${{ secrets.mail }}"
          git config user.name "${{ secrets.user }}"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated Terraform documentation"
            git push
          fi
