name: Terraform lint
on:
  push:
    branches:
      - "*"

jobs:
  TFLint_Linode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
    - name: Run Linode TFLint
      run: tflint linode/ --loglevel debug -f compact
  TFLint_AWS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
    - name: Run AWS TFLint
      run: tflint aws/ --loglevel debug -f compact

