name: Generate terraform docs
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

jobs:
  Create_Linode_documentation:
    name: Create Linode documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        working-dir: linode/
        output-file: USAGE.md
        output-method: inject
        git-push: "true"
        git-commit-message: "Updated Linode Usage.md file"
        git-push-user-email: ${{ secrets.mail }}
        git-push-user-name: ${{ secrets.user }}
  Create_AWS_documentation:
    name: Create AWS documentation
    needs: Create_Linode_documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docks inside the USAGE.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: aws/
          output-file: USAGE.md
          output-method: inject
          git-push: "true"
          git-commit-message: "Updated AWS Usage.md file"
          git-push-user-email: ${{ secrets.mail }}
          git-push-user-name: ${{ secrets.user }}
  Create_Azure_documentation:
    name: Create Azure documentation
    needs: Create_AWS_documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docks inside the USAGE.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: azure/
          output-file: USAGE.md
          output-method: inject
          git-push: "true"
          git-commit-message: "Updated Azure Usage.md file"
          git-push-user-email: ${{ secrets.mail }}
          git-push-user-name: ${{ secrets.user }}
